theme: jekyll-theme-minimal
lang        : "ru"
title: Сорокин Степан.
description : <span>1987 год рождения.<br><a href="mailto:stivsh@gmail.com">stivsh@gmail.com</a></span>
logo        : https://raw.githubusercontent.com/stivsh/stepan_sorokin.github.io/master/me.jpg
