theme: jekyll-theme-minimal
lang        : "ru"
title: Сорокин Степан Александрович.
description : 1987 год рождения.<br> stivsh@gmail.com <br> +7 (909) 417-78-65
logo        : https://raw.githubusercontent.com/stivsh/stepan_sorokin.github.io/master/me.jpg
author      : Сорокин Степан Александрович
email       : stivsh@gmail.com
