theme: jekyll-theme-minimal
lang        : "ru"
title: Сорокин Степан.
description : <span>1987 год рождения.<br><a href="mailto:stivsh@gmail.com">stivsh@gmail.com</a><br><a href="tel:+79094177865">+7 (909) 417-78-65</a></span>
logo        : https://raw.githubusercontent.com/stivsh/stepan_sorokin.github.io/master/me.jpg
author      : Сорокин Степан Александрович
email       : stivsh@gmail.com
