theme: jekyll-theme-minimal
lang        : "ru"
title: Сорокин Степан Александрович.
show_downloads: "false"
logo        :
description : Your awesome site
author      : Desired Persona
email       : your-email@domain.com
url         : ""
