theme: jekyll-theme-minimal
lang        : "ru"
title: Сорокин Степан Александрович.
description : bla bla
logo        : https://raw.githubusercontent.com/stivsh/stepan_sorokin.github.io/master/me.jpg
author      : Сорокин Степан Александрович
email       : stivsh@gmail.com
